#!/usr/bin/python
import sys
import os

sys.path.append( os.environ["HOME"] + "/.rotor/python" )
sys.path.append( os.environ["HOME"] + "/.rotor/lib" )
sys.path.append( "/usr/share/rotor/python" )
sys.path.append( "/usr/share/rotor/lib" )

import rotor 


if sys.argv[1] == "server":
  rotor.server( sys.argv[2] )
elif sys.argv[1] == "client":
  rotor.client( sys.argv[2] )
