#!/usr/bin/python

import shared_types
import rotorc
import os
import sys

#-------------------------------------------------------------------------------
# Registry setup
#-------------------------------------------------------------------------------

moduleName = os.path.basename( sys.argv[0] )
registry  = rotorc.RemoteRegistry( moduleName );

#-------------------------------------------------------------------------------
# Type registration
#-------------------------------------------------------------------------------

registry.registerMessageType( "poseMessage", shared_types.poseDeclaration )
registry.subscribeToMessage( "poseMessage", False, 4 )

#-------------------------------------------------------------------------------
# Main body
#-------------------------------------------------------------------------------


while True:
  try:
    message = registry.receiveMessage( 1.0 )
    if message.name() == "poseMessage":
      print message.data().x, message.data().y, message.data().z
      rotorc.Logger.info( message.data().toString() )
  except rotorc.MessagingTimeout:
    pass